development:
  sessions:
    default:
      database: beat-development
      hosts:
        - localhost:27017
test:
  sessions:
    default:
      database: beat-test
      hosts:
        - localhost:27017
      options:
        consistency: :strong
        # In the test environment we lower the retries and retry interval to
        # low amounts for fast failures.
        max_retries: 1
        retry_interval: 0
production:
  sessions:
    default:
      database: beat-production
      hosts:
        - localhost:27017
